update sources set country= 'AF' where country = 'AFGHANISTAN';
update sources set country= 'AX' where country = 'ÅLAND ISLANDS';
update sources set country= 'AL' where country = 'ALBANIA';
update sources set country= 'DZ' where country = 'ALGERIA';
update sources set country= 'AS' where country = 'AMERICAN SAMOA';
update sources set country= 'AD' where country = 'ANDORRA';
update sources set country= 'AO' where country = 'ANGOLA';
update sources set country= 'AI' where country = 'ANGUILLA';
update sources set country= 'AQ' where country = 'ANTARCTICA';
update sources set country= 'AG' where country = 'ANTIGUA AND BARBUDA';
update sources set country= 'AR' where country = 'ARGENTINA';
update sources set country= 'AM' where country = 'ARMENIA';
update sources set country= 'AW' where country = 'ARUBA';
update sources set country= 'AU' where country = 'AUSTRALIA';
update sources set country= 'AT' where country = 'AUSTRIA';
update sources set country= 'AZ' where country = 'AZERBAIJAN';
update sources set country= 'BS' where country = 'BAHAMAS';
update sources set country= 'BH' where country = 'BAHRAIN';
update sources set country= 'BD' where country = 'BANGLADESH';
update sources set country= 'BB' where country = 'BARBADOS';
update sources set country= 'BY' where country = 'BELARUS';
update sources set country= 'BE' where country = 'BELGIUM';
update sources set country= 'BZ' where country = 'BELIZE';
update sources set country= 'BJ' where country = 'BENIN';
update sources set country= 'BM' where country = 'BERMUDA';
update sources set country= 'BT' where country = 'BHUTAN';
update sources set country= 'BO' where country = 'BOLIVIA, PLURINATIONAL STATE OF';
update sources set country= 'BA' where country = 'BOSNIA AND HERZEGOVINA';
update sources set country= 'BW' where country = 'BOTSWANA';
update sources set country= 'BV' where country = 'BOUVET ISLAND';
update sources set country= 'BR' where country = 'BRAZIL';
update sources set country= 'IO' where country = 'BRITISH INDIAN OCEAN TERRITORY';
update sources set country= 'BN' where country = 'BRUNEI DARUSSALAM';
update sources set country= 'BG' where country = 'BULGARIA';
update sources set country= 'BF' where country = 'BURKINA FASO';
update sources set country= 'BI' where country = 'BURUNDI';
update sources set country= 'KH' where country = 'CAMBODIA';
update sources set country= 'CM' where country = 'CAMEROON';
update sources set country= 'CA' where country = 'CANADA';
update sources set country= 'CV' where country = 'CAPE VERDE';
update sources set country= 'KY' where country = 'CAYMAN ISLANDS';
update sources set country= 'CF' where country = 'CENTRAL AFRICAN REPUBLIC';
update sources set country= 'TD' where country = 'CHAD';
update sources set country= 'CL' where country = 'CHILE';
update sources set country= 'CN' where country = 'CHINA';
update sources set country= 'CX' where country = 'CHRISTMAS ISLAND';
update sources set country= 'CC' where country = 'COCOS (KEELING) ISLANDS';
update sources set country= 'CO' where country = 'COLOMBIA';
update sources set country= 'KM' where country = 'COMOROS';
update sources set country= 'CG' where country = 'CONGO';
update sources set country= 'CD' where country = 'CONGO, THE DEMOCRATIC REPUBLIC OF THE';
update sources set country= 'CK' where country = 'COOK ISLANDS';
update sources set country= 'CR' where country = 'COSTA RICA';
update sources set country= 'CI' where country = 'CÔTE D''IVOIRE';
update sources set country= 'HR' where country = 'CROATIA';
update sources set country= 'CU' where country = 'CUBA';
update sources set country= 'CY' where country = 'CYPRUS';
update sources set country= 'CZ' where country = 'CZECH REPUBLIC';
update sources set country= 'DK' where country = 'DENMARK';
update sources set country= 'DJ' where country = 'DJIBOUTI';
update sources set country= 'DM' where country = 'DOMINICA';
update sources set country= 'DO' where country = 'DOMINICAN REPUBLIC';
update sources set country= 'EC' where country = 'ECUADOR';
update sources set country= 'EG' where country = 'EGYPT';
update sources set country= 'SV' where country = 'EL SALVADOR';
update sources set country= 'GQ' where country = 'EQUATORIAL GUINEA';
update sources set country= 'ER' where country = 'ERITREA';
update sources set country= 'EE' where country = 'ESTONIA';
update sources set country= 'ET' where country = 'ETHIOPIA';
update sources set country= 'FK' where country = 'FALKLAND ISLANDS (MALVINAS)';
update sources set country= 'FO' where country = 'FAROE ISLANDS';
update sources set country= 'FJ' where country = 'FIJI';
update sources set country= 'FI' where country = 'FINLAND';
update sources set country= 'FR' where country = 'FRANCE';
update sources set country= 'GA' where country = 'GABON';
update sources set country= 'GM' where country = 'GAMBIA';
update sources set country= 'GE' where country = 'GEORGIA';
update sources set country= 'DE' where country = 'GERMANY';
update sources set country= 'GH' where country = 'GHANA';
update sources set country= 'GI' where country = 'GIBRALTAR';
update sources set country= 'GR' where country = 'GREECE';
update sources set country= 'GL' where country = 'GREENLAND';
update sources set country= 'GD' where country = 'GRENADA';
update sources set country= 'GP' where country = 'GUADELOUPE';
update sources set country= 'GU' where country = 'GUAM';
update sources set country= 'GT' where country = 'GUATEMALA';
update sources set country= 'GG' where country = 'GUERNSEY';
update sources set country= 'GN' where country = 'GUINEA';
update sources set country= 'GW' where country = 'GUINEA-BISSAU';
update sources set country= 'GY' where country = 'GUYANA';
update sources set country= 'HT' where country = 'HAITI';
update sources set country= 'HM' where country = 'HEARD ISLAND AND MCDONALD ISLANDS';
update sources set country= 'VA' where country = 'HOLY SEE (VATICAN CITY STATE)';
update sources set country= 'HN' where country = 'HONDURAS';
update sources set country= 'HK' where country = 'HONG KONG';
update sources set country= 'HU' where country = 'HUNGARY';
update sources set country= 'IS' where country = 'ICELAND';
update sources set country= 'IN' where country = 'INDIA';
update sources set country= 'ID' where country = 'INDONESIA';
update sources set country= 'IR' where country = 'IRAN, ISLAMIC REPUBLIC OF';
update sources set country= 'IQ' where country = 'IRAQ';
update sources set country= 'IE' where country = 'IRELAND';
update sources set country= 'IM' where country = 'ISLE OF MAN';
update sources set country= 'IL' where country = 'ISRAEL';
update sources set country= 'IT' where country = 'ITALY';
update sources set country= 'JM' where country = 'JAMAICA';
update sources set country= 'JP' where country = 'JAPAN';
update sources set country= 'JE' where country = 'JERSEY';
update sources set country= 'JO' where country = 'JORDAN';
update sources set country= 'KZ' where country = 'KAZAKHSTAN';
update sources set country= 'KE' where country = 'KENYA';
update sources set country= 'KI' where country = 'KIRIBATI';
update sources set country= 'KP' where country = 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF';
update sources set country= 'KR' where country = 'KOREA, REPUBLIC OF';
update sources set country= 'KW' where country = 'KUWAIT';
update sources set country= 'KG' where country = 'KYRGYZSTAN';
update sources set country= 'LA' where country = 'LAO PEOPLE''S DEMOCRATIC REPUBLIC';
update sources set country= 'LV' where country = 'LATVIA';
update sources set country= 'LB' where country = 'LEBANON';
update sources set country= 'LS' where country = 'LESOTHO';
update sources set country= 'LR' where country = 'LIBERIA';
update sources set country= 'LY' where country = 'LIBYAN ARAB JAMAHIRIYA';
update sources set country= 'LI' where country = 'LIECHTENSTEIN';
update sources set country= 'LT' where country = 'LITHUANIA';
update sources set country= 'LU' where country = 'LUXEMBOURG';
update sources set country= 'MO' where country = 'MACAO';
update sources set country= 'MK' where country = 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF';
update sources set country= 'MG' where country = 'MADAGASCAR';
update sources set country= 'MW' where country = 'MALAWI';
update sources set country= 'MY' where country = 'MALAYSIA';
update sources set country= 'MV' where country = 'MALDIVES';
update sources set country= 'ML' where country = 'MALI';
update sources set country= 'MT' where country = 'MALTA';
update sources set country= 'MH' where country = 'MARSHALL ISLANDS';
update sources set country= 'MQ' where country = 'MARTINIQUE';
update sources set country= 'MR' where country = 'MAURITANIA';
update sources set country= 'MU' where country = 'MAURITIUS';
update sources set country= 'YT' where country = 'MAYOTTE';
update sources set country= 'MX' where country = 'MEXICO';
update sources set country= 'FM' where country = 'MICRONESIA, FEDERATED STATES OF';
update sources set country= 'MD' where country = 'MOLDOVA, REPUBLIC OF';
update sources set country= 'MC' where country = 'MONACO';
update sources set country= 'MN' where country = 'MONGOLIA';
update sources set country= 'ME' where country = 'MONTENEGRO';
update sources set country= 'MS' where country = 'MONTSERRAT';
update sources set country= 'MA' where country = 'MOROCCO';
update sources set country= 'MZ' where country = 'MOZAMBIQUE';
update sources set country= 'MM' where country = 'MYANMAR';
update sources set country= 'NA' where country = 'NAMIBIA';
update sources set country= 'NR' where country = 'NAURU';
update sources set country= 'NP' where country = 'NEPAL';
update sources set country= 'NL' where country = 'NETHERLANDS';
update sources set country= 'AN' where country = 'NETHERLANDS ANTILLES';
update sources set country= 'NC' where country = 'NEW CALEDONIA';
update sources set country= 'NZ' where country = 'NEW ZEALAND';
update sources set country= 'NI' where country = 'NICARAGUA';
update sources set country= 'NE' where country = 'NIGER';
update sources set country= 'NG' where country = 'NIGERIA';
update sources set country= 'NU' where country = 'NIUE';
update sources set country= 'NF' where country = 'NORFOLK ISLAND';
update sources set country= 'MP' where country = 'NORTHERN MARIANA ISLANDS';
update sources set country= 'NO' where country = 'NORWAY';
update sources set country= 'OM' where country = 'OMAN';
update sources set country= 'PK' where country = 'PAKISTAN';
update sources set country= 'PW' where country = 'PALAU';
update sources set country= 'PS' where country = 'PALESTINIAN TERRITORY, OCCUPIED';
update sources set country= 'PA' where country = 'PANAMA';
update sources set country= 'PG' where country = 'PAPUA NEW GUINEA';
update sources set country= 'PY' where country = 'PARAGUAY';
update sources set country= 'PE' where country = 'PERU';
update sources set country= 'PH' where country = 'PHILIPPINES';
update sources set country= 'PN' where country = 'PITCAIRN';
update sources set country= 'PL' where country = 'POLAND';
update sources set country= 'PT' where country = 'PORTUGAL';
update sources set country= 'PR' where country = 'PUERTO RICO';
update sources set country= 'QA' where country = 'QATAR';
update sources set country= 'RE' where country = 'RÉUNION';
update sources set country= 'RO' where country = 'ROMANIA';
update sources set country= 'RU' where country = 'RUSSIAN FEDERATION';
update sources set country= 'RW' where country = 'RWANDA';
update sources set country= 'BL' where country = 'SAINT BARTHÉLEMY';
update sources set country= 'SH' where country = 'SAINT HELENA';
update sources set country= 'KN' where country = 'SAINT KITTS AND NEVIS';
update sources set country= 'LC' where country = 'SAINT LUCIA';
update sources set country= 'MF' where country = 'SAINT MARTIN';
update sources set country= 'PM' where country = 'SAINT PIERRE AND MIQUELON';
update sources set country= 'VC' where country = 'SAINT VINCENT AND THE GRENADINES';
update sources set country= 'WS' where country = 'SAMOA';
update sources set country= 'SM' where country = 'SAN MARINO';
update sources set country= 'ST' where country = 'SAO TOME AND PRINCIPE';
update sources set country= 'SA' where country = 'SAUDI ARABIA';
update sources set country= 'SN' where country = 'SENEGAL';
update sources set country= 'RS' where country = 'SERBIA';
update sources set country= 'SC' where country = 'SEYCHELLES';
update sources set country= 'SL' where country = 'SIERRA LEONE';
update sources set country= 'SG' where country = 'SINGAPORE';
update sources set country= 'SK' where country = 'SLOVAKIA';
update sources set country= 'SI' where country = 'SLOVENIA';
update sources set country= 'SB' where country = 'SOLOMON ISLANDS';
update sources set country= 'SO' where country = 'SOMALIA';
update sources set country= 'ZA' where country = 'SOUTH AFRICA';
update sources set country= 'GS' where country = 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS';
update sources set country= 'ES' where country = 'SPAIN';
update sources set country= 'LK' where country = 'SRI LANKA';
update sources set country= 'SD' where country = 'SUDAN';
update sources set country= 'SR' where country = 'SURINAME';
update sources set country= 'SJ' where country = 'SVALBARD AND JAN MAYEN';
update sources set country= 'SZ' where country = 'SWAZILAND';
update sources set country= 'SE' where country = 'SWEDEN';
update sources set country= 'CH' where country = 'SWITZERLAND';
update sources set country= 'SY' where country = 'SYRIAN ARAB REPUBLIC';
update sources set country= 'TW' where country = 'TAIWAN, PROVINCE OF CHINA';
update sources set country= 'TJ' where country = 'TAJIKISTAN';
update sources set country= 'TZ' where country = 'TANZANIA, UNITED REPUBLIC OF';
update sources set country= 'TH' where country = 'THAILAND';
update sources set country= 'TL' where country = 'TIMOR-LESTE';
update sources set country= 'TG' where country = 'TOGO';
update sources set country= 'TK' where country = 'TOKELAU';
update sources set country= 'TO' where country = 'TONGA';
update sources set country= 'TT' where country = 'TRINIDAD AND TOBAGO';
update sources set country= 'TN' where country = 'TUNISIA';
update sources set country= 'TR' where country = 'TURKEY';
update sources set country= 'TM' where country = 'TURKMENISTAN';
update sources set country= 'TC' where country = 'TURKS AND CAICOS ISLANDS';
update sources set country= 'TV' where country = 'TUVALU';
update sources set country= 'UG' where country = 'UGANDA';
update sources set country= 'UA' where country = 'UKRAINE';
update sources set country= 'AE' where country = 'UNITED ARAB EMIRATES';
update sources set country= 'GB' where country = 'UNITED KINGDOM';
update sources set country= 'US' where country = 'UNITED STATES';
update sources set country= 'UY' where country = 'URUGUAY';
update sources set country= 'UZ' where country = 'UZBEKISTAN';
update sources set country= 'VU' where country = 'VANUATU';
update sources set country= 'VE' where country = 'VENEZUELA, BOLIVARIAN REPUBLIC OF';
update sources set country= 'VN' where country = 'VIET NAM';
update sources set country= 'VG' where country = 'VIRGIN ISLANDS, BRITISH';
update sources set country= 'VI' where country = 'VIRGIN ISLANDS, U.S.';
update sources set country= 'WF' where country = 'WALLIS AND FUTUNA';
update sources set country= 'EH' where country = 'WESTERN SAHARA';
update sources set country= 'YE' where country = 'YEMEN';
update sources set country= 'ZM' where country = 'ZAMBIA';
update sources set country= 'ZW' where country = 'ZIMBABWE';
update sources set country= 'PS' where country = 'palestine';
update sources set country= 'HK' where country = 'HONG KONG - china';
update sources set country= 'MK' where country = 'MACEDONIA';
update sources set country= 'CD' where country = 'CONGO, DR';
update sources set country= 'MD' where country = 'MOLDOVA';
update sources set country= 'TW' where country = 'TAIWAN';
update sources set country= 'VE' where country = 'VENEZUELA';
update sources set country= 'IR' where country = 'IRAN';
update sources set country= 'TZ' where country = 'TANZANIA';
update sources set country= 'SY' where country = 'SYRIA';
update sources set country= 'TZ' where country = 'TANZANIA';
update sources set country= 'xx' where country = '(unknown)';
update sources set country= 'xx' where country = 'country';
update sources set country= 'xx' where country = '';
update sources set country= 'KP' where country = 'Korea, People''''s Republic';
update sources set country= 'BO' where country = 'BOLIVIA';
update sources set country= 'TL' where country = 'TIMOR LESTE';
update sources set country= 'CI' where country = 'COTE D''''IVOIRE';
update sources set country= 'CH' where country = 'SWITZERLAN';
update sources set country= 'VA' where country = 'HOLY SEE';
update sources set country= 'UK' where country = 'NORTHERN IRELAND';
update sources set country= 'LY' where country = 'Libya';
update sources set country= 'KV' where country = 'Kosovo';









