#!/bin/sh
### BEGIN INIT INFO
# Provides:          solr
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Should-Start:      $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop solr server
### END INIT INFO
# chkconfig: 2345 90 10
# description: Start/stop solr server

if ( [ -f /lib/lsb/init-functions ] )
then
	# Debian / unbuntu
	. /lib/lsb/init-functions
else
	# Centos / Redhat
	. /etc/init.d/functions  
fi

# You will probably want to change only two following lines.
BASEDIR="/opt/solr"
PORT="8983"
PROG="solr"
CMD="bin/solr"
RETVAL=0
 
start () {
    echo -n "Starting ${PROG} "
    cd ${BASEDIR}
    ${CMD} start -p ${PORT} > /dev/null &
    echo
}

stop () {
    echo -n "Stopping ${PROG} "
    cd ${BASEDIR}
   ${CMD} stop -p ${PORT} > /dev/null &
    echo
}

restart () {
    stop
    start
}


# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    RETVAL=2
    ;;
esac

exit $RETVAL
